# Read the docs here: https://pre-commit.com and http://jorisroovers.github.io/gitlint/
# Install hooks to your clone:
#   $ pre-commit install --install-hooks
# and
#   $ pre-commit install --install-hooks -t commit-msg

default_stages: [commit]
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: no-commit-to-branch
        args: ['--branch=stage/latest', '--pattern=stage/*']
      - id: trailing-whitespace

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
        name: Commit message check
        language: python
        entry: gitlint --msg-filename
        stages: [commit-msg]

# kate: indent-width 2; tab-width 2;
